producer_show_products:
    path: /{_locale}/producer/product
    controller: App\Controller\ProducerController::show_products
    requirements: 
        _locale: en|fr|lu
        
producer_add_product:
    path: /{_locale}/producer/product/add
    controller: App\Controller\ProducerController::add_product
    requirements: 
        _locale: en|fr|lu



producer_delete_products:
    path: /{_locale}/producer/product/delete
    controller: App\Controller\ProducerController::delete_product
    requirements: 
        _locale: en|fr|lu