producer_add_product:
    path: /{_locale}/producer
    controller: App\Controller\ProducerController::add_product
    requirements: 
        _locale: en|fr|lu

producer_show_products:
    path: /{_locale}/producer/show
    controller: App\Controller\ProducerController::show_products
    requirements: 
        _locale: en|fr|lu

producer_create_products:
    path: /{_locale}/producer/create
    controller: App\Controller\ProducerController::create_product
    requirements: 
        _locale: en|fr|lu

member_products:
    path: /{_locale}/member
    controller: App\Controller\MemberController::week
    requirements: 
        _locale: en|fr|lu